#!/usr/bin/expect

set timeout 20

set value [lindex $argv 0]

spawn /usr/share/kibana/bin/kibana-keystore add elasticsearch.password
expect {
	"already exists. Overwrite?" {
		send "y\r"
		exp_continue
	} "Enter value for elasticsearch.password" {
		send "$value\r"
		exp_continue
	} timeout {
		puts "Timeout reached. The password has not been added."
	} eof {
		exit
	} 
}