#!/usr/bin/expect

set timeout 120

set value [lindex $argv 0]

spawn /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash add ES_PWD
expect {
	"already exists. Overwrite?" {
		send "y\r"
		exp_continue
	} "nter value for" {
		send "$value\r"
		exp_continue
	} "Value cannot be empty" {
		puts "No data supplied, exiting the script"
		exit
	} "Added" {
		exit
	} timeout {
		puts "Timeout reached. The user has not been added."
	} eof {
		exit
	} 
}