#!/usr/bin/expect

set timeout 20

spawn /usr/share/elasticsearch/bin/elasticsearch-keystore create
expect {
	"An elasticsearch keystore already exists. Overwrite?" {
		send "n\r"
		exp_continue
	} "Created elasticsearch keystore" {
		exit
	} timeout {
		puts "Timeout reached. The keystore has not been checked."
	} eof {
		exit
	}
}