#!/usr/bin/expect

set timeout 60

spawn /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash create
expect {
	"keystore already exists" {
		send "n\r"
		exp_continue
	} "ontinue without password protection on the keystore" {
		send "y\r"
		exp_continue
	} "Created Logstash keystore at" {
		exit
	} timeout {
		puts "Timeout reached. The keystore has not been created."
	} eof {
		exit
	}
}