#!/usr/bin/expect

set timeout 10

spawn /usr/share/kibana/bin/kibana-keystore create
expect {
	"A Kibana keystore already exists. Overwrite?" {
		send "n\r"
		exp_continue
	} "Created Kibana keystore" {
		exit
	} timeout {
		puts "Timeout reached. The keystore has not been checked."
	} eof {
		exit
	}
}