#!/usr/bin/expect

set timeout 20

set value [lindex $argv 0]

spawn /usr/share/elasticsearch/bin/elasticsearch-reset-password -i -b -u kibana_system
expect {
	"nter password for" {
		send "$value\r"
		exp_continue
	} "successfully reset" {
		exit
	} timeout {
		puts "Timeout reached. The password has not been reset."
	}
}